version:
services:
	webapp:
		build:
		context: .
	    ports: "5000:80"
		dockerfile: Dockerfile
		image: jaganrajagopal/CRUDdotnetcore
		depends:
			-db
	db:
		image:"mcr.microsoft.com/mssql/server"
		envirnoment:
			SQLSERVER_SA_PASSWORD: "Newton@108"
            ACCEPT_EULA: "Y"
			
		ports:
			- "1433:1433"