version: '3.4'
services:
  webapps:
    image: jaganrajagopal/crudmvc 
	ports:
		- "8080:80"
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
	envirnoment:
		SQLSERVER_SA_PASSWORD: "Newton@108"
		ACCEPT_EULA: "Y"		
    ports:
      - "1433:1433"
	

      