version: '3.4'
services:
  webapps:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
	    - "8080:80"
	depends_on:
		- db
  db:
	image: "mcr.microsoft.com/mssql/server"
	envirnoment:
		SQLSERVER_SA_PASSWORD: "Newton@108"
		ACCEPT_EULA: "Y"			
	ports:
		- "1433:1433"