##### https://github.com/msepahvand/dotnetcore-docker/blob/master/docker-compose.yml
version: "2"
services:
    web:
        build: .
        ports:
            - "8080:80"       
        image: jaganrajagopal/crudmvc
        links:
            - db
        cpu_shares: 300
        mem_limit: 512m
        environment:
            SQLSERVER_HOST: "db"            
            SA_PASSWORD: "Newton@108"
    db:
        image: "microsoft/mssql-server-linux"
        cpu_shares: 300
        mem_limit: 1024m
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Newton@108"
            ACCEPT_EULA: "Y"      